BEGIN;

DROP TABLE IF EXISTS criterion CASCADE ;
DROP TABLE IF EXISTS event_members CASCADE;
DROP TABLE IF EXISTS holidays_status CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS user_group CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS blocks CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP TYPE gender;
DROP TYPE goal;
DROP TYPE status;

COMMIT;
