# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_create_group(self) -> None:
        """Test case for create_group

        create new group
        """
        pass

    def test_delete_group(self) -> None:
        """Test case for delete_group

        delete group
        """
        pass

    def test_get_group(self) -> None:
        """Test case for get_group

        group by name
        """
        pass

    def test_join_group(self) -> None:
        """Test case for join_group

        join group
        """
        pass

    def test_leave_group(self) -> None:
        """Test case for leave_group

        leave group
        """
        pass


if __name__ == '__main__':
    unittest.main()
