# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.models.create_event400_response import CreateEvent400Response

class TestCreateEvent400Response(unittest.TestCase):
    """CreateEvent400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEvent400Response:
        """Test CreateEvent400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEvent400Response`
        """
        model = CreateEvent400Response()
        if include_optional:
            return CreateEvent400Response(
                var_field = '',
                message = ''
            )
        else:
            return CreateEvent400Response(
        )
        """

    def testCreateEvent400Response(self):
        """Test CreateEvent400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
