# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.api.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()

    def tearDown(self) -> None:
        pass

    def test_create_event(self) -> None:
        """Test case for create_event

        create new event
        """
        pass

    def test_delete_event(self) -> None:
        """Test case for delete_event

        delete event
        """
        pass

    def test_get_user_events(self) -> None:
        """Test case for get_user_events

        events by user id
        """
        pass

    def test_review_event(self) -> None:
        """Test case for review_event

        review event
        """
        pass


if __name__ == '__main__':
    unittest.main()
