# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_block_user(self) -> None:
        """Test case for block_user

        block user
        """
        pass

    def test_cancel_user_holiday(self) -> None:
        """Test case for cancel_user_holiday

        set or reset holiday
        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        create new user
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        user by username
        """
        pass

    def test_set_user_holiday(self) -> None:
        """Test case for set_user_holiday

        set holiday
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        update user
        """
        pass


if __name__ == '__main__':
    unittest.main()
