# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.models.create_event500_response import CreateEvent500Response

class TestCreateEvent500Response(unittest.TestCase):
    """CreateEvent500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEvent500Response:
        """Test CreateEvent500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEvent500Response`
        """
        model = CreateEvent500Response()
        if include_optional:
            return CreateEvent500Response(
                error = ''
            )
        else:
            return CreateEvent500Response(
        )
        """

    def testCreateEvent500Response(self):
        """Test CreateEvent500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
