# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.models.update_user200_response import UpdateUser200Response

class TestUpdateUser200Response(unittest.TestCase):
    """UpdateUser200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUser200Response:
        """Test UpdateUser200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUser200Response`
        """
        model = UpdateUser200Response()
        if include_optional:
            return UpdateUser200Response(
                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                city = '',
                full_name = '',
                gender = '',
                goal = '',
                groups = [
                    random_coffe_client.models.group.Group(
                        id = 56, 
                        name = '', )
                    ],
                id = 56,
                interests = '',
                photo_url = '',
                position = '',
                socials = '',
                user_name = ''
            )
        else:
            return UpdateUser200Response(
                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                city = '',
                full_name = '',
                gender = '',
                goal = '',
                groups = [
                    random_coffe_client.models.group.Group(
                        id = 56, 
                        name = '', )
                    ],
                id = 56,
                interests = '',
                photo_url = '',
                position = '',
                socials = '',
                user_name = '',
        )
        """

    def testUpdateUser200Response(self):
        """Test UpdateUser200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
