# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.models.user_events_response_body import UserEventsResponseBody

class TestUserEventsResponseBody(unittest.TestCase):
    """UserEventsResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserEventsResponseBody:
        """Test UserEventsResponseBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserEventsResponseBody`
        """
        model = UserEventsResponseBody()
        if include_optional:
            return UserEventsResponseBody(
                events = [
                    random_coffe_client.models.event.Event(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        id = 56, 
                        name = '', 
                        users = [
                            random_coffe_client.models.user.User(
                                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                city = '', 
                                full_name = '', 
                                gender = '', 
                                goal = '', 
                                groups = [
                                    random_coffe_client.models.group.Group(
                                        id = 56, 
                                        name = '', )
                                    ], 
                                id = 56, 
                                interests = '', 
                                photo_url = '', 
                                position = '', 
                                socials = '', 
                                user_name = '', )
                            ], )
                    ]
            )
        else:
            return UserEventsResponseBody(
                events = [
                    random_coffe_client.models.event.Event(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        id = 56, 
                        name = '', 
                        users = [
                            random_coffe_client.models.user.User(
                                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                city = '', 
                                full_name = '', 
                                gender = '', 
                                goal = '', 
                                groups = [
                                    random_coffe_client.models.group.Group(
                                        id = 56, 
                                        name = '', )
                                    ], 
                                id = 56, 
                                interests = '', 
                                photo_url = '', 
                                position = '', 
                                socials = '', 
                                user_name = '', )
                            ], )
                    ],
        )
        """

    def testUserEventsResponseBody(self):
        """Test UserEventsResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
