# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from random_coffe_client.models.update_user_request_body import UpdateUserRequestBody

class TestUpdateUserRequestBody(unittest.TestCase):
    """UpdateUserRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserRequestBody:
        """Test UpdateUserRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserRequestBody`
        """
        model = UpdateUserRequestBody()
        if include_optional:
            return UpdateUserRequestBody(
                var_schema = '',
                city = '',
                full_name = '',
                id = 56,
                interests = '',
                photo_url = '',
                position = ''
            )
        else:
            return UpdateUserRequestBody(
                city = '',
                full_name = '',
                id = 56,
                interests = '',
                photo_url = '',
                position = '',
        )
        """

    def testUpdateUserRequestBody(self):
        """Test UpdateUserRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
